name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'backend/**/*.py'
      - 'backend/pyproject.toml'
      - 'backend/uv.lock'
      - '.github/workflows/backend.yml'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'backend/**/*.py'
      - 'backend/pyproject.toml'
      - 'backend/uv.lock'
      - '.github/workflows/backend.yml'

jobs:
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/astral-sh/uv:python3.12-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: apk add --no-cache gcc musl-dev linux-headers
      - name: Run Ruff checks
        run: cd backend && uv run --dev ruff format --check

  test:
    needs: ruff
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/astral-sh/uv:python3.12-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies and create test user
        run: |
          apk add --no-cache postgresql postgresql-dev gcc musl-dev linux-headers shadow
          adduser -D -u 1000 testuser
          chown -R testuser .
      - name: Run tests as testuser
        run: su - testuser -c "cd $PWD/backend && uv run --group dev pytest"
